import jax
import jax.numpy as jnp
from jax.experimental import optimizers
from jax.experimental.stax import Dense, Relu, Initializer
from jax.experimental.stax import BatchNorm
from jax.experimental.stax import Flatten
from jax.experimental.stax import Conv
from jax.experimental.stax import MaxPool
from jax.experimental.stax import Dense as DenseLayer
from jax.experimental.stax import Conv as ConvLayer
from jax.experimental.stax import MaxPool as MaxPoolLayer
from jax.experimental.stax import BatchNorm as BatchNormLayer
from jax.experimental.stax import Flatten as FlattenLayer
from jax.experimental.stax import Relu as ReLU
from jax.experimental.stax import Initializer as InitializerFunc
from jax.experimental.stax import Initializer as InitializerClass
from jax.experimental.stax import Initializer as InitializerDict
from jax.experimental.stax import Initializer as InitializerTuple
from jax.experimental.stax import Initializer as InitializerList
from jax.experimental.stax import Initializer as InitializerSet
from jax.experimental.stax import Initializer as InitializerFrozenSet
from jax.experimental.stax import Initializer as InitializerMapping
from jax.experimental.stax import Initializer as InitializerSequence
from jax.experimental.stax import Initializer as InitializerGenerator
from jax.experimental.stax import Initializer as InitializerCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutine
from jax.experimental.stax import Initializer as InitializerAsyncCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGeneratorCoroutineGenerator
